In [3]:
import numpy as numpy
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [4]:
credit_card_data = pd.read_csv("/content/creditcard.csv")

In [5]:
credit_card_data.head(10)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0
5,2,-0.425966,0.960523,1.141109,-0.168252,0.420987,-0.029728,0.476201,0.260314,-0.568671,...,-0.208254,-0.559825,-0.026398,-0.371427,-0.232794,0.105915,0.253844,0.081080,3.67,0.0
6,4,1.229658,0.141004,0.045371,1.202613,0.191881,0.272708,-0.005159,0.081213,0.464960,...,-0.167716,-0.270710,-0.154104,-0.780055,0.750137,-0.257237,0.034507,0.005168,4.99,0.0
7,7,-0.644269,1.417964,1.074380,-0.492199,0.948934,0.428118,1.120631,-3.807864,0.615375,...,1.943465,-1.015455,0.057504,-0.649709,-0.415267,-0.051634,-1.206921,-1.085339,40.80,0.0
8,7,-0.894286,0.286157,-0.113192,-0.271526,2.669599,3.721818,0.370145,0.851084,-0.392048,...,-0.073425,-0.268092,-0.204233,1.011592,0.373205,-0.384157,0.011747,0.142404,93.20,0.0
9,9,-0.338262,1.119593,1.044367,-0.222187,0.499361,-0.246761,0.651583,0.069539,-0.736727,...,-0.246914,-0.633753,-0.120794,-0.385050,-0.069733,0.094199,0.246219,0.083076,3.68,0.0

In [6]:
credit_card_data.tail(10)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
7963,10979,1.249706,-0.079696,0.824921,0.322643,-0.900948,-0.827550,-0.512295,-0.136281,1.906148,...,-0.082834,-0.031431,-0.008790,0.328556,0.177531,1.037839,-0.096713,0.003006,15.95,0.0
7964,10979,-2.334560,1.861316,0.164384,-0.816969,-1.402592,-0.549793,-1.206648,1.690017,0.688121,...,0.239931,0.277885,-0.000503,0.008197,-0.360606,0.822897,-0.646044,-0.102000,14.95,0.0
7965,10979,1.360989,-0.261996,0.541808,-0.226020,-1.184130,-1.287877,-0.744504,-0.233571,0.673276,...,-0.080677,-0.116942,0.059339,0.552663,0.265519,-0.338759,-0.005598,0.038366,15.95,0.0
7966,10979,1.227077,-0.064970,0.750337,0.131700,-0.617948,-0.319905,-0.552983,-0.028506,1.513247,...,-0.037820,0.112270,-0.067607,0.024850,0.218476,1.034218,-0.094322,-0.007826,15.95,0.0
7967,10980,-0.046786,0.030050,2.037794,-0.670130,-0.727283,-0.588537,-0.067966,-0.370767,0.228931,...,0.264364,1.078896,-0.097768,0.375679,-0.500253,-0.159051,-0.018267,-0.061794,39.00,0.0
7968,10980,1.284388,-0.013181,0.646174,0.198985,-0.568675,-0.526121,-0.448235,-0.167709,1.773223,...,-0.101868,-0.030298,-0.081412,-0.123281,0.278808,1.064001,-0.090181,0.000481,15.95,0.0
7969,10981,1.190428,-0.122329,0.954945,0.267101,-0.971026,-0.652279,-0.612992,-0.003909,1.633117,...,-0.015001,0.127027,0.012079,0.534409,0.112179,1.004483,-0.100188,-0.004774,14.95,0.0
7970,10981,-0.725175,0.298202,1.824761,-2.587170,0.283605,-0.016617,0.153659,0.045084,-0.197611,...,-0.017097,-0.070535,-0.442861,-0.895837,0.624743,-0.510601,-0.031142,0.025564,12.95,0.0
7971,10981,1.226153,-0.129645,0.735197,0.142752,-0.703245,-0.349641,-0.612641,0.020507,1.648986,...,-0.047936,0.040196,-0.057391,-0.012386,0.187685,1.037786,-0.100081,-0.009869,15.95,0.0
7972,10981,1.145381,-0.059349,0.968088,0.267891,-0.822582,-0.597727,-0.450197,-0.119747,1.338188,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7973 entries, 0 to 7972
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    7973 non-null   int64
 1   V1      7973 non-null   float64
 2   V2      7973 non-null   float64
 3   V3      7973 non-null   float64
 4   V4      7973 non-null   float64
 5   V5      7973 non-null   float64
 6   V6      7973 non-null   float64
 7   V7      7973 non-null   float64
 8   V8      7973 non-null   float64
 9   V9      7973 non-null   float64
 10  V10     7973 non-null   float64
 11  V11     7973 non-null   float64
 12  V12     7973 non-null   float64
 13  V13     7973 non-null   float64
 14  V14     7973 non-null   float64
 15  V15     7972 non-null   float64
 16  V16     7972 non-null   float64
 17  V17     7972 non-null   float64
 18  V18     7972 non-null   float64
 19  V19     7972 non-null   float64
 20  V20     7972 non-null   float64
 21  V21     7972 non-null   float64
 22  V22     7972 non-null   float64
 23  V23     7972 non-null   float64
 24  V24     7972 non-null   float64
 25  V25     7972 non-null   float64
 26  V26     7972 non-null   float64
 27  V27     7972 non-null   float64
 28  V28     7972 non-null   float64
 29  Amount  7972 non-null   float64
 30  Class   7972 non-null   float64
dtypes: float64(30), int64(1)
memory usage: 1.9 MB

In [8]:
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [9]:
credit_card_data["Class"].value_counts()

Class
0.0    7947
1.0      25
Name: count, dtype: int64

In [10]:
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [11]:
print(legit.shape)
print(fraud.shape)

(7947, 31)
(25, 31)

In [12]:
legit.head(5)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [13]:
fraud.head(5)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
541,406,-2.312227,1.951992,-1.609851,3.997906,-0.522188,-1.426545,-2.537387,1.391657,-2.770089,...,0.517232,-0.035049,-0.465211,0.320198,0.044519,0.177840,0.261145,-0.143276,0.00,1.0
623,472,-3.043541,-3.157307,1.088463,2.288644,1.359805,-1.064823,0.325574,-0.067794,-0.270953,...,0.661696,0.435477,1.375966,-0.293803,0.279798,-0.145362,-0.252773,0.035764,529.00,1.0
4920,4462,-2.303350,1.759247,-0.359745,2.330243,-0.821628,-0.075788,0.562320,-0.399147,-0.238253,...,-0.294166,-0.932391,0.172726,-0.087330,-0.156114,-0.542628,0.039566,-0.153029,239.93,1.0
6108,6986,-4.397974,1.358367,-2.592844,2.679787,-1.128131,-1.706536,-3.496197,-0.248778,-0.247768,...,0.573574,0.176968,-0.436207,-0.053502,0.252405,-0.657488,-0.827136,0.849573,59.00,1.0
6329,7519,1.234235,3.019740,-4.304597,4.732795,3.624201,-1.357746,1.713445,-0.496358,-1.282858,...,-0.379068,-0.704181,-0.656805,-1.632653,1.488901,0.566797,-0.010016,0.146793,1.00,1.0

In [14]:
legit.Amount.describe()

count    7947.000000
mean       65.284891
std       194.126547
min         0.000000
25%         4.795000
50%        15.950000
75%        54.990000
max      7712.430000
Name: Amount, dtype: float64

In [15]:
fraud.Amount.describe()

count      25.000000
mean      106.308400
std       372.676883
min         0.000000
25%         1.000000
50%         1.000000
75%         1.000000
max      1809.680000
Name: Amount, dtype: float64

In [16]:
credit_card_data.groupby("Class").mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,4246.546496,-0.297235,0.286979,0.917142,0.201968,-0.023263,0.164019,-0.019547,-0.072779,0.662196,...,0.042418,-0.055123,-0.165485,-0.034918,0.026636,0.088960,0.019511,0.014875,0.000417,65.284891
1.0,7359.240000,-1.154048,2.930880,-4.757618,4.590240,-0.636103,-1.952536,-2.202403,0.647916,-1.581984,...,0.263011,0.393614,-0.265715,-0.116502,-0.183413,0.067479,0.256994,0.421586,0.237600,106.308400

In [17]:
legit_sample = legit.sample(n=492)

In [18]:
new_dataset = pd.concat([legit_sample,fraud], axis=0)

In [19]:
new_dataset.head(5)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
1132,878,-1.173804,0.281004,2.101093,-0.724886,0.024482,0.300528,0.288660,0.233967,0.258240,...,-0.046837,0.064206,-0.146279,-0.312220,0.257629,0.351120,0.130965,-0.082722,69.70,0.0
4722,4155,-0.476035,1.090266,1.804199,0.202625,-0.018658,-0.569692,0.526677,-0.007487,0.923830,...,-0.333163,-0.639631,0.069099,0.308496,-0.346676,0.043375,0.252188,0.113657,5.25,0.0
4112,3743,-0.822606,0.018450,0.517564,-2.747390,2.183296,3.220683,-0.411817,0.872444,-0.184630,...,-0.262830,-0.877610,-0.079385,0.898458,0.464195,-0.572050,0.227741,0.118311,36.37,0.0
7790,10845,-1.284658,1.241122,1.559619,-1.436445,0.168177,-0.509973,0.692338,-0.215617,1.617182,...,-0.344199,-0.287677,-0.122351,-0.008195,-0.185912,0.666091,0.377243,0.167550,21.00,0.0
7109,9316,-0.678814,0.085682,3.372475,0.534177,-0.473904,1.095169,-0.556677,0.374624,2.730737,...,0.006200,0.817897,-0.388787,-0.034077,0.009394,-0.378541,0.008767,-0.098968,1.18,0.0

In [20]:
new_dataset.shape

(517, 31)

In [21]:
new_dataset["Class"].value_counts()

Class
0.0    492
1.0     25
Name: count, dtype: int64

In [22]:
new_dataset.groupby("Class").mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,4146.833333,-0.240986,0.217456,0.968552,0.298694,-0.044397,0.245388,-0.053955,-0.021837,0.585959,...,0.078184,-0.063090,-0.167292,-0.053779,-0.050191,0.082622,0.050078,0.003442,0.00232,74.498598
1.0,7359.240000,-1.154048,2.930880,-4.757618,4.590240,-0.636103,-1.952536,-2.202403,0.647916,-1.581984,...,0.263011,0.393614,-0.265715,-0.116502,-0.183413,0.067479,0.256994,0.421586,0.23760,106.308400

In [23]:
X = new_dataset.drop(columns="Class",axis=1)
Y = new_dataset["Class"]

In [24]:
print(X)

       Time        V1        V2        V3        V4        V5        V6  \
1132    878 -1.173804  0.281004  2.101093 -0.724886  0.024482  0.300528
4722   4155 -0.476035  1.090266  1.804199  0.202625 -0.018658 -0.569692
4112   3743 -0.822606  0.018450  0.517564 -2.747390  2.183296  3.220683
7790  10845 -1.284658  1.241122  1.559619 -1.436445  0.168177 -0.509973
7109   9316 -0.678814  0.085682  3.372475  0.534177 -0.473904  1.095169
...     ...       ...       ...       ...       ...       ...       ...
6870   8757 -1.863756  3.442644 -4.468260  2.805336 -2.118412 -2.332285
6882   8808 -4.617217  1.695694 -3.114372  4.328199 -1.873257 -0.989908
6899   8878 -2.661802  5.856393 -7.653616  6.379742 -0.060712 -3.131550
6903   8886 -2.535852  5.793644 -7.618463  6.395830 -0.065210 -3.136372
6971   9064 -3.499108  0.258555 -4.489558  4.853894 -6.974522  3.628382

            V7        V8        V9  ...       V20       V21       V22  \
1132  0.288660  0.233967  0.258240  ...  0.261922 -0.046837  0.064206
4722  0.526677 -0.007487  0.923830  ... -0.011148 -0.333163 -0.639631
4112 -0.411817  0.872444 -0.184630  ...  0.421950 -0.262830 -0.877610
7790  0.692338 -0.215617  1.617182  ...  0.506709 -0.344199 -0.287677
7109 -0.556677  0.374624  2.730737  ... -0.193426  0.006200  0.817897
...        ...       ...       ...  ...       ...       ...       ...
6870 -4.261237  1.701682 -1.439396  ...  0.360924  0.667927 -0.516242
6882 -4.577265  0.472216  0.472017  ... -0.039046  0.481830  0.146023
6899 -3.103570  1.778492 -3.831154  ...  0.399097  0.734775 -0.435901
6903 -3.104557  1.823233 -3.878658  ...  0.408704  0.716720 -0.448060
6971  5.431271 -1.946734 -0.775680  ... -3.042626 -1.052368  0.204817

           V23       V24       V25       V26       V27       V28   Amount
1132 -0.146279 -0.312220  0.257629  0.351120  0.130965 -0.082722    69.70
4722  0.069099  0.308496 -0.346676  0.043375  0.252188  0.113657     5.25
4112 -0.079385  0.898458  0.464195 -0.572050  0.227741  0.118311    36.37
7790 -0.122351 -0.008195 -0.185912  0.666091  0.377243  0.167550    21.00
7109 -0.388787 -0.034077  0.009394 -0.378541  0.008767 -0.098968     1.18
...        ...       ...       ...       ...       ...       ...      ...
6870 -0.012218  0.070614  0.058504  0.304883  0.418012  0.208858     1.00
6882  0.117039 -0.217565 -0.138776 -0.424453 -1.002041  0.890780     1.10
6899 -0.384766 -0.286016  1.007934  0.413196  0.280284  0.303937     1.00
6903 -0.402407 -0.288835  1.011752  0.425965  0.413140  0.308205     1.00
6971 -2.119007  0.170279 -0.393844  0.296367  1.985913 -0.900452  1809.68

[517 rows x 30 columns]

In [25]:
print(Y)

1132    0.0
4722    0.0
4112    0.0
7790    0.0
7109    0.0
       ...
6870    1.0
6882    1.0
6899    1.0
6903    1.0
6971    1.0
Name: Class, Length: 517, dtype: float64

In [26]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

In [27]:
model = LogisticRegression()

In [28]:
model.fit(X_train,Y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [29]:
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction,Y_train)

In [30]:
print("Accuracy on Training Data : ", training_data_accuracy)

Accuracy on Training Data :  1.0

In [31]:
training_data_f1_score = f1_score(X_train_prediction,Y_train)

In [32]:
print("F1 Score on Training Data : ", training_data_f1_score)

F1 Score on Training Data :  1.0

In [33]:
training_data_confusion_matrix = confusion_matrix(X_train_prediction,Y_train)

In [34]:
print("Confusion Matrix on Training Data : ", training_data_confusion_matrix)

Confusion Matrix on Training Data :  [[393   0]
 [  0  20]]

In [35]:
training_data_classification_report = classification_report(X_train_prediction,Y_train)

In [36]:
print("Classification Report on Training Data : ", training_data_classification_report)

Classification Report on Training Data :                precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       393
         1.0       1.00      1.00      1.00        20

    accuracy                           1.00       413
   macro avg       1.00      1.00      1.00       413
weighted avg       1.00      1.00      1.00       413

In [37]:
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction,Y_test)

In [38]:
print("Accuracy on Test Data : ", test_data_accuracy)

Accuracy on Test Data :  0.9903846153846154

In [39]:
test_data_f1_score = f1_score(X_test_prediction,Y_test)

In [40]:
print("F1 Score on Test Data : ", test_data_f1_score)

F1 Score on Test Data :  0.8888888888888888

In [41]:
test_data_confusion_matrix = confusion_matrix(X_test_prediction,Y_test)

In [42]:
print("Confusion Matrix on Test Data : ", test_data_confusion_matrix)

Confusion Matrix on Test Data :  [[99  1]
 [ 0  4]]

In [43]:
test_data_classification_report = classification_report(X_test_prediction,Y_test)

In [44]:
print("Classification Report on Test Data : ", test_data_classification_report)

Classification Report on Test Data :                precision    recall  f1-score   support

         0.0       1.00      0.99      0.99       100
         1.0       0.80      1.00      0.89         4

    accuracy                           0.99       104
   macro avg       0.90      0.99      0.94       104
weighted avg       0.99      0.99      0.99       104